### ISSUE TITLE
可否分享一下生成API代码的工具？

### ISSUE THREAD

**Issue by oh0123** [amzapi/selling-partner-api-sdk#2]
你好，请问是如何通过json文件生成代码库中的代码模版的？我觉得十分简洁，清爽，可否分享一下工具？或者有什么学习途径吗？作为菜鸟十分好奇，感激！

**Comment by dominikznidar** [comment]
@wanghao0123 they seem to be embedding some code from this repo https://github.com/deepmap/oapi-codegen so you can use that as a starting point.

**Comment by gopkg-dev** [comment]
It is here 
https://github.com/amzapi/gosdk-codegen

**Comment by oh0123** [comment]
thanks @gopkg-dev

**Comment by oh0123** [comment]
@dominikznidar thanks anyway https://github.com/amzapi/gosdk-codegen is better for this project.
