### ISSUE TITLE
NumberOfItems type is different from the response of actually

### ISSUE THREAD

**Issue by xiaxiaosheng** [amzapi/selling-partner-api-sdk#3]
https://github.com/gopkg-dev/selling-partner-api-sdk/tree/master/ordersV0
types.gen.go:123 
GetOrderItemsResponse.Payload.OrderItems.ProductInfo.ProductInfoDetail.NumberOfItems 
At types.gen.go:529, the type of NumberOfItems is *int, but the actually response is string

**Comment by gopkg-dev** [comment]
https://github.com/gopkg-dev/selling-partner-api-sdk/blob/cf9bdde067d8ef6e33eafc1dc3e607ecd05a0b60/ordersV0/types.gen.go#L532

https://github.com/amzn/selling-partner-api-models/issues/1110

It's good.

**Comment by gopkg-dev** [comment]
please update the latest package.

`go get -u gopkg.me/selling-partner-api-sdk`

**Comment by xiaxiaosheng** [comment]
Thanks for your prompt reply!
