### ISSUE TITLE
Working example get report

### ISSUE THREAD

**Issue by mbolder** [amzapi/selling-partner-api-sdk#31]
Hi, 
my experience with go is quite limited, since I just moved from python to go. 
Is there a chance you could give a working example for a request / download of a report e.g.  

GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING. 

Your first example the markets works, but I cannot retrieve a report yet. 

Thank you very much in advance.

**Comment by daic11** [comment]
Have you solved this problem? I also tried to implement the second example with no success.
What is "amzn.GetReportDocumentResponse" it is never mentioned before in code, what I should include?
And what is reportType variable?

I can't understand this in code.

> Hi, my experience with go is quite limited, since I just moved from python to go. Is there a chance you could give a working example for a request / download of a report e.g.
> 
> GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING.
> 
> Your first example the markets works, but I cannot retrieve a report yet.
> 
> Thank you very much in advance.

**Comment by daic11** [comment]
@amzapi

**Comment by gopkg-dev** [comment]
> Have you solved this problem? I also tried to implement the second example with no success. What is "amzn.GetReportDocumentResponse" it is never mentioned before in code, what I should include? And what is reportType variable?
> 
> I can't understand this in code.
> 
> > Hi, my experience with go is quite limited, since I just moved from python to go. Is there a chance you could give a working example for a request / download of a report e.g.
> > GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING.
> > Your first example the markets works, but I cannot retrieve a report yet.
> > Thank you very much in advance.

https://developer-docs.amazon.com/sp-api/docs/report-type-values

**Comment by daic11** [comment]
@gopkg-dev Could you also please help with sale.GetOrderMetricsWithResponse(ctx, SECOND_PARAMETER).
What should I provide with this second parameter?


```
`sale, err := sales.NewClientWithResponses(endpoint,
		sales.WithHTTPClient(client),
		sales.WithRequestBefore(func(ctx context.Context, req *http.Request) error {
			req.Header.Add("X-Amzn-Requestid", uuid.New().String())
			err = sellingPartner.AuthorizeRequest(req)
			if err != nil {
				return errors.Wrap(err, "sign error")
			}
			dump, err := httputil.DumpRequest(req, true)
			if err != nil {
				return errors.Wrap(err, "DumpRequest Error")
			}
			log.Printf("DumpRequest = %s", dump)
			return nil
		}),
		sales.WithResponseAfter(func(ctx context.Context, rsp *http.Response) error {

			dump, err := httputil.DumpResponse(rsp, true)
			if err != nil {
				return errors.Wrap(err, "DumpResponse Error")
			}
			log.Printf("DumpResponse = %s", dump)
			return nil
		}),
	)
	if err != nil {
		panic(err)
	}

  ctx := context.Background()

  _, err := sale.GetOrderMetricsWithResponse(ctx, sales.GetOrderMetricsParams.)
`


```

**Comment by daic11** [comment]
Okay, I get now.  sales.GetOrderMetricsParams - this is a structure which I should create before with required parameters.

After that I should put it as a second pointer parameter.

**Comment by daic11** [comment]
> > Have you solved this problem? I also tried to implement the second example with no success. What is "amzn.GetReportDocumentResponse" it is never mentioned before in code, what I should include? And what is reportType variable?
> > I can't understand this in code.
> > > Hi, my experience with go is quite limited, since I just moved from python to go. Is there a chance you could give a working example for a request / download of a report e.g.
> > > GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING.
> > > Your first example the markets works, but I cannot retrieve a report yet.
> > > Thank you very much in advance.
> 
> https://developer-docs.amazon.com/sp-api/docs/report-type-values

Could you please help?

**Is it okay to use GET_MERCHANT_LISTINGS_DATA as reportDocumentId?**

**I get this error with the following code "Service returned a status that isn't 2xx: 400"** :

```
func main() {

	sellingPartner, err := sp.NewSellingPartner(&sp.Config{
		ClientID:     clientID,
		ClientSecret: clientSecret,
		RefreshToken: refreshToken,
	})
	if err != nil {
		panic(err)
	}

	report, err := reports.NewClientWithResponses(endpoint,
		reports.WithRequestBefore(func(ctx context.Context, req *http.Request) error {
			err = sellingPartner.AuthorizeRequest(req)
			if err != nil {
				return errors.Wrap(err, "sign error")
			}
			dump, err := httputil.DumpRequest(req, true)
			if err != nil {
				return errors.Wrap(err, "DumpRequest Error")
			}
			os.WriteFile("test-samples/3dumpedThirdPartyReqGetReports.txt", dump, 0777)
			return nil
		}),
		reports.WithResponseAfter(func(ctx context.Context, rsp *http.Response) error {
			dump, err := httputil.DumpResponse(rsp, true)
			if err != nil {
				return errors.Wrap(err, "DumpResponse Error")
			}
			os.WriteFile("test-samples/3dumpedThirdPartyRespGetReports.txt", dump, 0777)
			return nil
		}),
	)
	if err != nil {
		log.Fatal("Failed to create NewClientWithResponses: ", err)
	}
	ctx := context.Background()

	reportDocumentId := "GET_MERCHANT_LISTINGS_DATA"
	resp, err := report.GetReportDocument(ctx, reportDocumentId)
	if err != nil {
		log.Fatal("Failed to make GetReportDocument request: ", err)
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		log.Fatal("Service returned a status that isn't 2xx: ", resp.StatusCode)
	}
	defer resp.Body.Close()
}
```

**Comment by daic11** [comment]
> > > Have you solved this problem? I also tried to implement the second example with no success. What is "amzn.GetReportDocumentResponse" it is never mentioned before in code, what I should include? And what is reportType variable?
> > > I can't understand this in code.
> > > > Hi, my experience with go is quite limited, since I just moved from python to go. Is there a chance you could give a working example for a request / download of a report e.g.
> > > > GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING.
> > > > Your first example the markets works, but I cannot retrieve a report yet.
> > > > Thank you very much in advance.
> > 
> > 
> > https://developer-docs.amazon.com/sp-api/docs/report-type-values
> 
> Could you please help?
> 
> **Is it okay to use GET_MERCHANT_LISTINGS_DATA as reportDocumentId?**
> 
> **I get this error with the following code "Service returned a status that isn't 2xx: 400"** :
> 
> ```
> func main() {
> 
> 	sellingPartner, err := sp.NewSellingPartner(&sp.Config{
> 		ClientID:     clientID,
> 		ClientSecret: clientSecret,
> 		RefreshToken: refreshToken,
> 	})
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	report, err := reports.NewClientWithResponses(endpoint,
> 		reports.WithRequestBefore(func(ctx context.Context, req *http.Request) error {
> 			err = sellingPartner.AuthorizeRequest(req)
> 			if err != nil {
> 				return errors.Wrap(err, "sign error")
> 			}
> 			dump, err := httputil.DumpRequest(req, true)
> 			if err != nil {
> 				return errors.Wrap(err, "DumpRequest Error")
> 			}
> 			os.WriteFile("test-samples/3dumpedThirdPartyReqGetReports.txt", dump, 0777)
> 			return nil
> 		}),
> 		reports.WithResponseAfter(func(ctx context.Context, rsp *http.Response) error {
> 			dump, err := httputil.DumpResponse(rsp, true)
> 			if err != nil {
> 				return errors.Wrap(err, "DumpResponse Error")
> 			}
> 			os.WriteFile("test-samples/3dumpedThirdPartyRespGetReports.txt", dump, 0777)
> 			return nil
> 		}),
> 	)
> 	if err != nil {
> 		log.Fatal("Failed to create NewClientWithResponses: ", err)
> 	}
> 	ctx := context.Background()
> 
> 	reportDocumentId := "GET_MERCHANT_LISTINGS_DATA"
> 	resp, err := report.GetReportDocument(ctx, reportDocumentId)
> 	if err != nil {
> 		log.Fatal("Failed to make GetReportDocument request: ", err)
> 	}
> 	if resp.StatusCode < 200 || resp.StatusCode > 299 {
> 		log.Fatal("Service returned a status that isn't 2xx: ", resp.StatusCode)
> 	}
> 	defer resp.Body.Close()
> }
> ```

@gopkg-dev @amzapi

**Comment by gopkg-dev** [comment]
Here is the step-by-step process to request and retrieve a report using the Amazon SP-API:

1. **Create a Report**:
   - Use the `createReport` endpoint to request a report.
   - Method: `POST`
   - URL: `/reports/2021-06-30/reports`
   - Example request body:
     ```json
     {
       "reportType": "GET_MERCHANT_LISTINGS_DATA",
       "marketplaceIds": ["ATVPDKIKX0DER"]
     }
     ```
   - The response will include a `reportId`.

2. **Poll Amazon SQS Queue**:
   - Periodically poll the Amazon SQS queue for the `REPORT_PROCESSING_FINISHED` notification event.
   - This event will indicate the report status as `CANCELLED`, `DONE`, or `FATAL`.
   - If the report processing is `DONE`, the event will include a `reportDocumentId`.

3. **Get Report Document**:
   - Use the `getReportDocument` endpoint to retrieve the document using the `reportDocumentId`.
   - Method: `GET`
   - URL: `/reports/2021-06-30/documents/{reportDocumentId}`
   - Replace `{reportDocumentId}` with the actual ID received from the SQS notification.

4. **Download the Report**:
   - The `getReportDocument` response returns a pre-signed URL and the compression algorithm used.
   - Use the pre-signed URL to download the report.

This process will allow you to request, retrieve, and download a report from Amazon SP-API.

You can refer to the documentation for more details and any additional parameters you might need.

https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-tutorial-request-a-report#tutorial-request-and-retrieve-a-report

https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-verify-that-the-report-processing-is-complete

**Comment by daic11** [comment]
> Here is the step-by-step process to request and retrieve a report using the Amazon SP-API:
> 
>     1. **Create a Report**:
>        
>        * Use the `createReport` endpoint to request a report.
>        * Method: `POST`
>        * URL: `/reports/2021-06-30/reports`
>        * Example request body:
>          ```json
>          {
>            "reportType": "GET_MERCHANT_LISTINGS_DATA",
>            "marketplaceIds": ["ATVPDKIKX0DER"]
>          }
>          ```
>        * The response will include a `reportId`.
> 
>     2. **Poll Amazon SQS Queue**:
>        
>        * Periodically poll the Amazon SQS queue for the `REPORT_PROCESSING_FINISHED` notification event.
>        * This event will indicate the report status as `CANCELLED`, `DONE`, or `FATAL`.
>        * If the report processing is `DONE`, the event will include a `reportDocumentId`.
> 
>     3. **Get Report Document**:
>        
>        * Use the `getReportDocument` endpoint to retrieve the document using the `reportDocumentId`.
>        * Method: `GET`
>        * URL: `/reports/2021-06-30/documents/{reportDocumentId}`
>        * Replace `{reportDocumentId}` with the actual ID received from the SQS notification.
> 
>     4. **Download the Report**:
>        
>        * The `getReportDocument` response returns a pre-signed URL and the compression algorithm used.
>        * Use the pre-signed URL to download the report.
> 
> 
> This process will allow you to request, retrieve, and download a report from Amazon SP-API.
> 
> You can refer to the documentation for more details and any additional parameters you might need.
> 
> https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-tutorial-request-a-report#tutorial-request-and-retrieve-a-report
> 
> https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-verify-that-the-report-processing-is-complete

Amazing, thank you!!!
