### ISSUE TITLE
Please provide license for go.pkg.dev

### ISSUE THREAD

**Issue by dominikznidar** [amzapi/selling-partner-api-sdk#7]
Please define some license on the project to allow pkg.go.dev (linked to in [README.md](https://github.com/amzapi/selling-partner-api-sdk/blob/master/README.md)) to display the documentation.

Example: https://pkg.go.dev/gopkg.me/selling-partner-api-sdk@master/pkg/selling-partner

Details about the package not displayed as the license is missing.

You can check their [license policy](https://pkg.go.dev/license-policy) for more details.

**Comment by pzduniak** [comment]
https://github.com/amzapi/selling-partner-api-sdk/commit/f5cb002759973b386a3c88a00729eccfcc124c8d

Looks like that's done.

**Comment by dominikznidar** [comment]
Closing as the issue is already resolved with https://github.com/amzapi/selling-partner-api-sdk/commit/f5cb002759973b386a3c88a00729eccfcc124c8d#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7
